import React, { FormEvent, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, Ambulance, ArrowUp, Baby, Bot, Brain, CalendarCheck, CheckCircle2, ChevronRight, ClipboardCheck, CloudUpload, Droplets, MessageCircle, HeartPulse, Menu, Moon, Pill, Quote, ShieldCheck, Share2, Sparkles, Star, Stethoscope, Sun, Users, Venus, X, Zap } from 'lucide-react';
import './index.css';

type Theme = 'light' | 'dark';
const disclaimer = 'This website is for educational and demonstration purposes only. It does not provide medical diagnosis or treatment. Please consult a qualified healthcare professional for medical advice.';
const doctors = ['Dr. Ava Williams - Cardiologist', 'Dr. Noah Patel - General Physician', 'Dr. Mia Chen - Dermatologist', 'Dr. Sofia Rivera - Mental Health'];
const chartData = [{day:'Mon',score:72,steps:7200},{day:'Tue',score:76,steps:8100},{day:'Wed',score:70,steps:6900},{day:'Thu',score:84,steps:9600},{day:'Fri',score:82,steps:9000},{day:'Sat',score:88,steps:11200},{day:'Sun',score:86,steps:10400}];
const iconClass = 'h-7 w-7 text-cyan-500';

function Section({ id, title, eyebrow, children }: {id:string; title:string; eyebrow?:string; children:React.ReactNode}) {
  return <section id={id} className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6}} className="mb-10 text-center">{eyebrow && <p className="mb-3 font-semibold uppercase tracking-[.25em] text-cyan-500">{eyebrow}</p>}<h2 className="text-3xl font-black tracking-tight text-slate-950 dark:text-white md:text-5xl">{title}</h2></motion.div>{children}</section>;
}
function Card({ children, className='' }: {children:React.ReactNode; className?:string}) {return <motion.article whileHover={{y:-8,scale:1.01}} className={`glass rounded-3xl p-6 shadow-xl shadow-cyan-900/5 ${className}`}>{children}</motion.article>}
function Nav({theme,setTheme}:{theme:Theme;setTheme:(t:Theme)=>void}){const [open,setOpen]=useState(false); const links=['home','about','ai-features','services','appointment','testimonials','contact']; return <header className="sticky top-0 z-50 border-b border-white/40 bg-white/75 backdrop-blur-xl dark:border-slate-700/40 dark:bg-slate-950/75"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><a href="#home" className="flex items-center gap-2 text-xl font-black text-slate-950 dark:text-white"><span className="rounded-2xl bg-gradient-to-br from-blue-600 to-emerald-400 p-2 text-white"><HeartPulse/></span>MediScan AI</a><div className="hidden items-center gap-6 lg:flex">{links.map(l=><a key={l} href={`#${l}`} className="text-sm font-semibold capitalize text-slate-600 hover:text-cyan-500 dark:text-slate-300">{l.replace('-',' ')}</a>)}<button aria-label="Toggle dark mode" onClick={()=>setTheme(theme==='dark'?'light':'dark')} className="rounded-full border p-2 dark:border-slate-700">{theme==='dark'?<Sun/>:<Moon/>}</button></div><button aria-label="Open navigation" className="lg:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>{open&&<div className="grid gap-3 px-6 pb-5 lg:hidden">{links.map(l=><a onClick={()=>setOpen(false)} key={l} href={`#${l}`} className="capitalize">{l.replace('-',' ')}</a>)}</div>}</header>}
function Hero() {
  return (
    <section id="home" className="relative overflow-hidden bg-gradient-to-br from-blue-50 via-cyan-50 to-emerald-50 dark:from-slate-950 dark:via-slate-900 dark:to-cyan-950">
      <div className="absolute inset-0 bg-cyan-100/40 dark:bg-cyan-950/20" aria-hidden="true" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-10 px-4 py-24 lg:grid-cols-2">
        <motion.div initial={{ opacity: 0, x: -30 }} animate={{ opacity: 1, x: 0 }}>
          <p className="mb-4 inline-flex rounded-full bg-white/70 px-4 py-2 text-sm font-bold text-cyan-700 shadow">AI triage • smart reports • virtual care</p>
          <h1 className="text-5xl font-black tracking-tight text-slate-950 dark:text-white md:text-7xl">AI-Powered Healthcare for Everyone</h1>
          <p className="mt-6 text-lg leading-8 text-slate-600 dark:text-slate-300">A premium demo platform that blends beautiful product design with realistic AI healthcare workflows for faster, clearer patient experiences.</p>
          <div className="mt-8 flex flex-wrap gap-4">
            <a href="#symptom-demo" className="rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 px-7 py-4 font-bold text-white shadow-lg shadow-cyan-500/30">Try AI Symptom Checker</a>
            <a href="#appointment" className="rounded-full border border-cyan-200 bg-white px-7 py-4 font-bold text-cyan-700 dark:bg-slate-900">Book Appointment</a>
          </div>
        </motion.div>
        <motion.div animate={{ y: [0, -12, 0] }} transition={{ repeat: Infinity, duration: 5 }} className="glass rounded-[2.5rem] p-8">
          <div className="rounded-[2rem] bg-gradient-to-br from-white to-cyan-100 p-8 dark:from-slate-800 dark:to-cyan-950">
            <Stethoscope className="h-24 w-24 text-cyan-500" />
            <h3 className="mt-6 text-3xl font-black dark:text-white">Smart care cockpit</h3>
            <div className="mt-6 grid gap-3">
              {['Instant risk guidance', 'Report highlights', 'Doctor matching'].map((item) => (
                <div key={item} className="flex items-center gap-3 rounded-2xl bg-white/70 p-3 dark:bg-slate-900/70">
                  <CheckCircle2 className="text-emerald-500" />
                  {item}
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
function App(){const [theme,setTheme]=useState<Theme>('light'); return <div className={`${theme} bg-white text-slate-700 dark:bg-slate-950 dark:text-slate-200`}><Nav theme={theme} setTheme={setTheme}/><Hero/><Stats/><About/><AIFeatures/><Services/><Dashboard/><Appointment/><Testimonials/><FAQ/><Newsletter/><Contact/><Chatbot/><a aria-label="Back to top" href="#home" className="fixed bottom-5 left-5 rounded-full bg-cyan-500 p-3 text-white shadow-lg"><ArrowUp/></a><Footer/></div>}
function Stats(){return <Section id="stats" title="Trusted demo outcomes" eyebrow="impact"><div className="grid gap-5 md:grid-cols-4">{[['24/7','AI support'],['92%','demo satisfaction'],['18k+','mock scans'],['4.9★','patient rating']].map(([n,l])=><Card key={l} className="text-center"><p className="text-4xl font-black text-cyan-500">{n}</p><p>{l}</p></Card>)}</div></Section>}
function About(){return <Section id="about" title="Built for clear, human-centered care" eyebrow="about"><div className="grid gap-6 lg:grid-cols-3"><Card><ShieldCheck className={iconClass}/><h3 className="mt-4 text-xl font-bold">Mission</h3><p>Make healthcare information easier to understand through safe educational AI demos, delightful design, and guided next steps.</p></Card><Card><Zap className={iconClass}/><h3 className="mt-4 text-xl font-bold">Vision</h3><p>A future where students, clinics, and innovators can prototype responsible digital health journeys with confidence.</p></Card><Card><Users className={iconClass}/><h3 className="mt-4 text-xl font-bold">Team</h3><p>Product designers, frontend engineers, AI learners, and medical-domain mentors collaborating on accessible technology.</p></Card></div><div className="mt-10 grid gap-6 lg:grid-cols-2"><Card><h3 className="text-2xl font-black">Why choose MediScan AI</h3><p className="mt-3">Responsive UI, realistic mock workflows, privacy-first messaging, appointment booking, and dashboard analytics in one polished demo.</p></Card><Card><h3 className="text-2xl font-black">Timeline</h3><p className="mt-3">Research → prototype → AI feature demos → accessibility pass → Vercel/Replit-ready deployment.</p></Card></div></Section>}
function AIFeatures(){const features=[[Activity,'AI Symptom Checker'],[Brain,'Disease Risk Prediction'],[ClipboardCheck,'Medical Report Analyzer'],[Bot,'AI Medical Chatbot'],[HeartPulse,'Health Score Calculator'],[Pill,'Medicine Reminder'],[Sparkles,'Health Dashboard']]; return <Section id="ai-features" title="Interactive AI features" eyebrow="AI demos"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,name]:any)=><Card key={name}><Icon className={iconClass}/><h3 className="mt-4 text-xl font-black">{name}</h3><p className="mt-2">Explore a polished simulation with helpful explanations, careful disclaimers, and modern micro-interactions.</p><a href={name.includes('Symptom')?'#symptom-demo':'#dashboard'} className="mt-5 inline-flex items-center font-bold text-cyan-600">Demo button <ChevronRight size={18}/></a><p className="mt-4 text-xs text-slate-500">{disclaimer}</p></Card>)}</div><Demos/></Section>}
function analyzeSymptoms(input: string) {
  const text = input.toLowerCase();
  const checks = [
    { words: ['chest', 'pressure', 'breath', 'arm pain'], conditions: ['Cardiac strain', 'Acid reflux', 'Anxiety-related chest tightness'], risk: 'High', specialist: 'Cardiologist or emergency care', steps: ['Seek urgent medical help if chest pain is severe, crushing, or paired with breathlessness.', 'Avoid strenuous activity until assessed.', 'Track pain duration and triggers.'] },
    { words: ['fever', 'cough', 'sore throat', 'fatigue'], conditions: ['Viral upper respiratory infection', 'Seasonal flu', 'COVID-like respiratory illness'], risk: 'Moderate', specialist: 'General physician', steps: ['Rest and hydrate.', 'Monitor temperature and oxygen level if available.', 'Book a visit if fever persists beyond 3 days or breathing worsens.'] },
    { words: ['headache', 'migraine', 'dizziness', 'blurred'], conditions: ['Tension headache', 'Migraine episode', 'Dehydration or blood pressure variation'], risk: 'Moderate', specialist: 'Neurologist or primary care doctor', steps: ['Drink water and rest in a quiet room.', 'Check blood pressure if possible.', 'Get urgent help for sudden severe headache, weakness, or confusion.'] },
    { words: ['rash', 'itch', 'skin', 'redness'], conditions: ['Allergic dermatitis', 'Fungal skin irritation', 'Eczema flare'], risk: 'Low to Moderate', specialist: 'Dermatologist', steps: ['Avoid scratching and new cosmetic products.', 'Keep the area clean and dry.', 'Consult a clinician if rash spreads, oozes, or includes fever.'] },
    { words: ['sad', 'anxiety', 'panic', 'sleep', 'stress'], conditions: ['Stress overload', 'Anxiety symptoms', 'Sleep disruption'], risk: 'Moderate', specialist: 'Mental health professional', steps: ['Try slow breathing and reduce stimulants.', 'Talk to a trusted person today.', 'Seek immediate crisis support if you may harm yourself or someone else.'] },
    { words: ['stomach', 'vomit', 'nausea', 'diarrhea'], conditions: ['Gastroenteritis', 'Food intolerance', 'Acidity or indigestion'], risk: 'Low to Moderate', specialist: 'Gastroenterologist or general physician', steps: ['Sip fluids frequently.', 'Eat light foods as tolerated.', 'Seek care for blood in stool, severe pain, or dehydration.'] },
  ];
  const match = checks.find((check) => check.words.some((word) => text.includes(word)));
  return match ?? { conditions: ['General wellness concern', 'Minor infection or lifestyle-related issue', 'Needs clinician review if persistent'], risk: input.trim() ? 'Low' : 'Not enough information', specialist: 'General physician', steps: input.trim() ? ['Add duration, severity, age, and any medicines for a better demo result.', 'Monitor symptoms and rest.', 'Book an appointment if symptoms persist or worsen.'] : ['Type symptoms such as fever, cough, headache, rash, chest pain, or anxiety.', 'Then click Analyze symptoms.', 'For emergencies, contact local emergency services immediately.'] };
}

function Demos() {
  const [sym, setSym] = useState('fever, cough, fatigue');
  const [result, setResult] = useState(() => analyzeSymptoms('fever, cough, fatigue'));
  const [risk, setRisk] = useState(38);
  const report = useMemo(() => ['Hemoglobin: normal', 'Vitamin D: low', 'WBC: slightly elevated'], []);

  return <div className="mt-12 grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-1" ><h3 id="symptom-demo" className="text-2xl font-black">Symptom Checker</h3><p className="mt-2 text-sm">Enter symptoms in plain language and the demo engine will match them to a safe educational care pathway.</p><textarea aria-label="Enter symptoms" value={sym} onChange={e=>setSym(e.target.value)} className="mt-4 min-h-28 w-full rounded-2xl border p-4 text-slate-900"/><button type="button" onClick={()=>setResult(analyzeSymptoms(sym))} className="mt-3 w-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 px-5 py-3 font-bold text-white shadow-lg shadow-cyan-500/20">Analyze symptoms</button><div className="mt-4 rounded-2xl bg-cyan-50 p-4 text-sm text-slate-700"><p><b>Possible conditions:</b> {result.conditions.join(', ')}.</p><p className="mt-2"><b>Risk level:</b> {result.risk}</p><p className="mt-2"><b>Suggested specialist:</b> {result.specialist}</p><div className="mt-2"><b>Recommended next steps:</b><ul className="mt-1 list-disc pl-5">{result.steps.map((step)=><li key={step}>{step}</li>)}</ul></div></div><p className="mt-3 text-xs">{disclaimer}</p></Card><Card><h3 className="text-2xl font-black">Risk Prediction</h3><label className="mt-4 block">Simulated lifestyle risk: {risk}%<input aria-label="Risk slider" type="range" value={risk} onChange={e=>setRisk(Number(e.target.value))} className="w-full"/></label><ResponsiveContainer width="100%" height={160}><BarChart data={[{n:'Heart',v:risk},{n:'Diabetes',v:Math.max(15,risk-8)},{n:'Stress',v:risk+10}]}><Bar dataKey="v" fill="#06b6d4"/><XAxis dataKey="n"/><Tooltip/></BarChart></ResponsiveContainer><p className="text-sm">Recommendations: walk 30 minutes, reduce sodium, schedule preventive screening.</p></Card><Card><h3 className="text-2xl font-black">Report Analyzer</h3><label className="mt-4 flex cursor-pointer flex-col items-center rounded-2xl border-2 border-dashed border-cyan-300 p-6"><CloudUpload className="text-cyan-500"/>Upload PDF or image<input type="file" className="sr-only"/></label><ul className="mt-4 list-disc pl-5 text-sm">{report.map(r=><li key={r}>{r}</li>)}</ul><p className="mt-3 text-sm">AI explanation: findings may suggest inflammation and a need to discuss vitamin supplementation with a clinician.</p></Card></div>
}
function Services(){const s=[[Stethoscope,'General Consultation'],[HeartPulse,'Heart Disease Prediction'],[Droplets,'Diabetes Risk'],[Activity,'Skin Disease Analysis'],[Brain,'Mental Health Support'],[Venus,"Women's Health"],[Baby,'Child Healthcare'],[Ambulance,'Emergency Consultation']]; return <Section id="services" title="Care services" eyebrow="services"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{s.map(([Icon,n]:any)=><Card key={n}><Icon className={iconClass}/><h3 className="mt-3 font-black">{n}</h3><p className="text-sm">Fast educational triage flow with specialist guidance and appointment handoff.</p></Card>)}</div></Section>}
function Dashboard(){return <Section id="dashboard" title="Personal health dashboard" eyebrow="mock analytics"><div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><ResponsiveContainer width="100%" height={280}><AreaChart data={chartData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Area dataKey="score" stroke="#06b6d4" fill="#67e8f9"/><Area dataKey="steps" stroke="#10b981" fill="#bbf7d0"/></AreaChart></ResponsiveContainer></Card><div className="grid gap-4">{['BMI 23.4','Heart Rate 76 bpm','Blood Pressure 118/76','Sugar Level 94 mg/dL','Water 2.4L','Sleep 7.5h','Steps 9,840'].map(x=><Card key={x} className="py-4"><b>{x}</b></Card>)}</div></div></Section>}
function Appointment(){const [done,setDone]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setDone(true)}; return <Section id="appointment" title="Book an appointment" eyebrow="schedule"><form onSubmit={submit} className="glass mx-auto grid max-w-4xl gap-4 rounded-3xl p-6 shadow-xl md:grid-cols-2">{['Name','Email','Phone','Age'].map(x=><input required key={x} aria-label={x} placeholder={x} type={x==='Email'?'email':'text'} className="rounded-2xl border p-4 text-slate-900"/>)}<select aria-label="Gender" className="rounded-2xl border p-4 text-slate-900"><option>Female</option><option>Male</option><option>Prefer not to say</option></select><select aria-label="Doctor selection" className="rounded-2xl border p-4 text-slate-900">{doctors.map(d=><option key={d}>{d}</option>)}</select><input aria-label="Date picker" type="date" className="rounded-2xl border p-4 text-slate-900"/><input aria-label="Time picker" type="time" className="rounded-2xl border p-4 text-slate-900"/><textarea aria-label="Symptoms" placeholder="Describe symptoms" className="min-h-28 rounded-2xl border p-4 text-slate-900 md:col-span-2"/><button className="rounded-full bg-gradient-to-r from-emerald-500 to-cyan-500 px-6 py-4 font-bold text-white md:col-span-2">Submit booking</button>{done&&<p role="status" className="text-center font-bold text-emerald-500 md:col-span-2">Appointment request submitted successfully.</p>}</form></Section>}
function Testimonials(){return <Section id="testimonials" title="Patient stories" eyebrow="testimonials"><div className="grid gap-6 md:grid-cols-3">{['Priya S.','Marcus L.','Emma R.'].map((n,i)=><Card key={n}><img loading="lazy" alt={`${n} profile`} className="h-16 w-16 rounded-full object-cover" src={`https://images.unsplash.com/photo-${i===0?'1494790108377-be9c29b29330':i===1?'1500648767791-00dcc994a43e':'1438761681033-6461ffad8d80'}?auto=format&fit=crop&w=160&q=80`}/><div className="mt-3 flex text-amber-400">{Array.from({length:5}).map((_,j)=><Star key={j} fill="currentColor"/>)}</div><Quote className="mt-4 text-cyan-400"/><p>MediScan AI made the healthcare journey feel clear, friendly, and professional for our college demo.</p><b>{n}</b></Card>)}</div></Section>}
function FAQ(){return <Section id="faq" title="Frequently asked questions"><div className="mx-auto max-w-3xl space-y-4">{['Is this real diagnosis? No, it is an educational demonstration.','Can it be deployed? Yes, Vite works well on Vercel and Replit.','Is it responsive? Yes, layouts adapt across mobile, tablet, and desktop.'].map(q=><Card key={q}>{q}</Card>)}</div></Section>}
function Newsletter(){return <Section id="newsletter" title="Join the health innovation list"><div className="glass mx-auto flex max-w-2xl gap-3 rounded-full p-2"><input aria-label="Newsletter email" placeholder="Email address" className="min-w-0 flex-1 rounded-full px-5 text-slate-900"/><button className="rounded-full bg-blue-600 px-6 py-3 font-bold text-white">Subscribe</button></div></Section>}
function Contact(){return <Section id="contact" title="Contact MediScan AI" eyebrow="contact"><div className="grid gap-6 lg:grid-cols-2"><Card><form className="grid gap-4"><input aria-label="Contact name" placeholder="Name" className="rounded-2xl border p-4 text-slate-900"/><input aria-label="Contact email" placeholder="Email" className="rounded-2xl border p-4 text-slate-900"/><textarea aria-label="Contact message" placeholder="Message" className="min-h-32 rounded-2xl border p-4 text-slate-900"/><button className="rounded-full bg-cyan-500 px-6 py-3 font-bold text-white">Send message</button></form></Card><Card><p><b>Email:</b> hello@mediscan-ai.demo</p><p><b>Phone:</b> +1 (555) 019-2040</p><p><b>Address:</b> 120 Innovation Drive, San Francisco, CA</p><div className="mt-5 grid h-48 place-items-center rounded-3xl bg-gradient-to-br from-cyan-100 to-emerald-100 text-cyan-700">Google Maps placeholder</div><div className="mt-5 flex gap-4"><Share2/><MessageCircle/><Users/></div></Card></div></Section>}
function Chatbot(){const [open,setOpen]=useState(false); return <div className="fixed bottom-5 right-5 z-50"><button aria-label="Open AI chatbot" onClick={()=>setOpen(!open)} className="rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 p-4 text-white shadow-xl"><Bot/></button>{open&&<Card className="absolute bottom-16 right-0 w-80"><h3 className="font-black">AI Medical Chatbot</h3><p className="mt-3 text-sm">Hello! I can explain wellness concepts, suggest which specialist to consider, and remind you to seek professional care for urgent symptoms.</p><p className="mt-3 text-xs">{disclaimer}</p></Card>}</div>}
function Footer(){return <footer className="border-t border-slate-200 px-4 py-10 text-center dark:border-slate-800"><b>MediScan AI</b><p className="mt-2 text-sm">Premium AI healthcare demo for education, internships, and product showcases.</p></footer>}

createRoot(document.getElementById('root')!).render(<App/>);
