import React, { FormEvent, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, Ambulance, ArrowUp, Baby, Bot, Brain, CalendarCheck, CheckCircle2, ChevronRight, Heart, CloudUpload, Droplets, Share2, HeartPulse, Menu, Moon, Pill, Quote, ShieldCheck, Sparkles, Stethoscope, Sun, Users } from 'lucide-react';
import './index.css';

type Theme = 'light' | 'dark';
const disclaimer = 'This website is for educational and demonstration purposes only. It does not provide medical diagnosis or treatment. Please consult a qualified healthcare professional for medical advice.';
const doctors = ['Dr. Ava Williams - Cardiologist', 'Dr. Noah Patel - General Physician', 'Dr. Mia Chen - Dermatologist', 'Dr. Sofia Rivera - Mental Health'];
const chartData = [{day:'Mon',score:72,steps:7200},{day:'Tue',score:76,steps:8100},{day:'Wed',score:70,steps:6900},{day:'Thu',score:84,steps:9600},{day:'Fri',score:82,steps:9000},{day:'Sat',score:88,steps:10200},{day:'Sun',score:85,steps:9800}];
const iconClass = 'h-7 w-7 text-cyan-500';

function Section({ id, title, eyebrow, children }: {id:string; title:string; eyebrow?:string; children:React.ReactNode}) {
  return <section id={id} className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:0.5}}>{eyebrow&&<p className="mb-4 text-sm font-semibold uppercase text-cyan-600 dark:text-cyan-400">{eyebrow}</p>}<h2 className="text-4xl font-bold">{title}</h2>{children}</motion.div></section>
}
function Card({ children, className='' }: {children:React.ReactNode; className?:string}) {return <motion.article whileHover={{y:-8,scale:1.01}} className={`glass rounded-3xl p-6 shadow-xl shadow-cyan-500/10 dark:shadow-cyan-500/5 ${className}`}>{children}</motion.article>
}
function Nav({theme,setTheme}:{theme:Theme;setTheme:(t:Theme)=>void}){const [open,setOpen]=useState(false); const links=['home','about','ai-features','services','appointment','testimonials','contact']; return <nav className="sticky top-0 z-40 border-b border-slate-200 bg-white/80 backdrop-blur dark:border-slate-800 dark:bg-slate-950/80"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><h1 className="text-2xl font-bold">MediScan AI</h1><div className="hidden gap-8 md:flex">{links.map(l=><a href={`#${l}`} className="transition hover:text-cyan-600 dark:hover:text-cyan-400">{l}</a>)}</div><div className="flex items-center gap-4"><button onClick={()=>setTheme(theme==='light'?'dark':'light')} className="p-2 hover:bg-slate-100 rounded-lg dark:hover:bg-slate-800">{theme==='light'?<Moon className={iconClass}/>:<Sun className={iconClass}/>}</button><button className="md:hidden" onClick={()=>setOpen(!open)}><Menu className={iconClass}/></button></div>{open&&<div className="absolute left-0 right-0 top-16 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 p-4 flex flex-col gap-2">{links.map(l=><a href={`#${l}`} className="py-2 px-4 hover:bg-slate-100 dark:hover:bg-slate-800 rounded">{l}</a>)}</div>}</nav>
}
function Hero(){return <section id="home" className="relative overflow-hidden bg-gradient-to-br from-blue-50 via-cyan-50 to-emerald-50 dark:from-slate-950 dark:via-slate-900 dark:to-cyan-950"><div className="mx-auto max-w-7xl px-4 py-32 sm:px-6 lg:px-8"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:0.8}}><h2 className="text-6xl font-bold mb-6">AI-Powered Healthcare<br/>for Everyone</h2><p className="text-xl text-slate-600 dark:text-slate-300 mb-8 max-w-2xl">Experience the future of medical diagnosis with our advanced AI system. Educational demonstration for modern healthcare.</p><button className="bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-8 py-3 rounded-lg font-semibold hover:shadow-lg hover:shadow-cyan-500/50 transition">Get Started</button></motion.div></div></section>
}
function App(){const [theme,setTheme]=useState<Theme>('light'); return <div className={`${theme} bg-white text-slate-700 dark:bg-slate-950 dark:text-slate-200`}><Nav theme={theme} setTheme={setTheme}/><Hero/><Stats/><About/><AIFeatures/><Demos/><Services/><Dashboard/><Appointment/><Testimonials/><FAQ/><Newsletter/><Contact/><Chatbot/><Footer/></div>
}
function Stats(){return <Section id="stats" title="Trusted demo outcomes" eyebrow="impact"><div className="grid gap-5 md:grid-cols-4">{[['24/7','AI support'],['92%','demo satisfaction'],['18k+','medical records'],['99.9%','uptime']].map(([n,l])=><Card key={n}><h3 className="text-3xl font-bold text-cyan-600 dark:text-cyan-400">{n}</h3><p className="text-slate-600 dark:text-slate-400">{l}</p></Card>)}</div></Section>
}
function About(){return <Section id="about" title="Built for clear, human-centered care" eyebrow="about"><div className="grid gap-6 lg:grid-cols-3"><Card><ShieldCheck className={iconClass}/><h3 className="mt-4 text-lg font-semibold">Privacy First</h3><p className="text-slate-600 dark:text-slate-400 mt-2">Your data is encrypted and never shared. HIPAA compliant infrastructure.</p></Card><Card><Sparkles className={iconClass}/><h3 className="mt-4 text-lg font-semibold">AI Advanced</h3><p className="text-slate-600 dark:text-slate-400 mt-2">Machine learning models trained on millions of medical records.</p></Card><Card><Users className={iconClass}/><h3 className="mt-4 text-lg font-semibold">Doctor Verified</h3><p className="text-slate-600 dark:text-slate-400 mt-2">All insights reviewed by licensed medical professionals.</p></Card></div></Section>
}
function AIFeatures(){const features=[[Activity,'AI Symptom Checker'],[Brain,'Disease Risk Prediction'],[Heart,'Medical Report Analyzer'],[Bot,'AI Medical Chatbot'],[HeartPulse,'Health Score']]; return <Section id="ai-features" title="Powerful AI Features" eyebrow="capabilities"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-5">{features.map(([Icon,name])=><Card key={name}><Icon className={iconClass}/><h3 className="mt-4 font-semibold">{name}</h3></Card>)}</div></Section>
}
function Demos(){const [sym,setSym]=useState('fever, cough, fatigue'); const [risk,setRisk]=useState(38); const report=useMemo(()=>['Hemoglobin: normal','Vitamin D: low','WBC: slightly elevated'],[]), return <Section id="demos" title="Interactive Demos" eyebrow="try it"><div className="grid gap-6 lg:grid-cols-2"><Card><h3 className="font-semibold mb-4">Symptom Checker</h3><input value={sym} onChange={(e)=>setSym(e.target.value)} placeholder="Enter symptoms..." className="w-full p-3 rounded-lg border border-slate-300 dark:border-slate-600 dark:bg-slate-800"/><button className="mt-4 w-full bg-cyan-600 text-white py-2 rounded-lg hover:bg-cyan-700">Analyze Symptoms</button></Card><Card><h3 className="font-semibold mb-4">Disease Risk Score</h3><div className="text-4xl font-bold text-cyan-600 dark:text-cyan-400">{risk}%</div><p className="text-slate-600 dark:text-slate-400 mt-2">Based on health factors</p><input type="range" value={risk} onChange={(e)=>setRisk(Number(e.target.value))} className="w-full mt-4"/></Card></div></Section>
}
function Services(){const s=[[Stethoscope,'General Consultation'],[HeartPulse,'Heart Disease Prediction'],[Droplets,'Diabetes Risk'],[Activity,'Skin Disease Analysis'],[Brain,'Mental Health Support'],[Pill,'Medicine Guide']]; return <Section id="services" title="Our Services" eyebrow="services"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{s.map(([Icon,name])=><Card key={name}><Icon className={iconClass}/><h3 className="mt-4 font-semibold">{name}</h3><p className="text-slate-600 dark:text-slate-400 mt-2">Get instant AI-powered insights</p></Card>)}</div></Section>
}
function Dashboard(){return <Section id="dashboard" title="Personal health dashboard" eyebrow="mock analytics"><div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><ResponsiveContainer width="100%" height={300}><AreaChart data={chartData}><CartesianGrid stroke="#e2e8f0" strokeDasharray="0"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Area type="monotone" dataKey="score" stroke="#06b6d4" fill="#06b6d4" fillOpacity={0.1}/></AreaChart></ResponsiveContainer></Card><Card><h3 className="font-semibold mb-4">Today's Stats</h3><div className="space-y-4">{chartData.slice(0,1).map(d=><div key={d.day}><p className="text-slate-600 dark:text-slate-400">Steps: {d.steps}</p><p className="text-2xl font-bold mt-1">{d.score}</p></div>)}</div></Card></div></Section>
}
function Appointment(){const [done,setDone]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setDone(true)}; return <Section id="appointment" title="Book an appointment" eyebrow="schedule"><Card className="max-w-2xl mx-auto">{done?<p className="text-center text-lg font-semibold text-cyan-600">✓ Appointment request submitted!</p>:<form onSubmit={submit} className="space-y-4"><input required placeholder="Full name" className="w-full p-3 rounded-lg border border-slate-300 dark:border-slate-600 dark:bg-slate-800"/><input required type="email" placeholder="Email" className="w-full p-3 rounded-lg border border-slate-300 dark:border-slate-600 dark:bg-slate-800"/><select required className="w-full p-3 rounded-lg border border-slate-300 dark:border-slate-600 dark:bg-slate-800"><option>Select a doctor</option>{doctors.map(d=><option key={d}>{d}</option>)}</select><button type="submit" className="w-full bg-cyan-600 text-white py-3 rounded-lg hover:bg-cyan-700 font-semibold">Book Now</button></form>}</Card></Section>
}
function Testimonials(){return <Section id="testimonials" title="Patient stories" eyebrow="testimonials"><div className="grid gap-6 md:grid-cols-3">{['Priya S.','Marcus L.','Emma R.'].map((n,i)=><Card key={n}><Quote className={iconClass}/><p className="mt-4 italic text-slate-600 dark:text-slate-400">"{['The AI diagnosis was surprisingly accurate!','Finally, accessible healthcare for everyone.','Best medical app I\'ve used.'][i]}"</p><p className="mt-4 font-semibold">{n}</p></Card>)}</div></Section>
}
function FAQ(){return <Section id="faq" title="Frequently asked questions"><div className="mx-auto max-w-3xl space-y-4">{['Is this real diagnosis? No, it is an educational demonstration.','Can it replace doctors? No, always consult healthcare professionals.','How accurate is the AI? ~92% accuracy on demo data.','Is my data safe? Yes, all data is encrypted.'].map((q,i)=><Card key={i}><h3 className="font-semibold">{q.split('?')[0]}?</h3><p className="text-slate-600 dark:text-slate-400 mt-2">{q.split('? ')[1]}</p></Card>)}</div></Section>
}
function Newsletter(){return <Section id="newsletter" title="Join the health innovation list"><div className="glass mx-auto flex max-w-2xl gap-3 rounded-full p-2"><input aria-label="Newsletter email" placeholder="your@email.com" type="email" className="flex-1 bg-transparent px-4 py-2 outline-none"/><button className="rounded-full bg-gradient-to-r from-cyan-500 to-blue-500 px-6 py-2 font-semibold text-white hover:shadow-lg hover:shadow-cyan-500/50">Subscribe</button></div></Section>
}
function Contact(){return <Section id="contact" title="Contact MediScan AI" eyebrow="contact"><div className="grid gap-6 lg:grid-cols-2"><Card><form className="grid gap-4"><input aria-label="Contact name" placeholder="Your name" className="w-full p-3 rounded-lg border border-slate-300 dark:border-slate-600 dark:bg-slate-800"/><input aria-label="Contact email" placeholder="your@email.com" type="email" className="w-full p-3 rounded-lg border border-slate-300 dark:border-slate-600 dark:bg-slate-800"/><textarea aria-label="Contact message" placeholder="Your message" rows={4} className="w-full p-3 rounded-lg border border-slate-300 dark:border-slate-600 dark:bg-slate-800"/><button type="submit" className="bg-cyan-600 text-white py-2 rounded-lg hover:bg-cyan-700 font-semibold">Send Message</button></form></Card><Card><h3 className="font-semibold mb-4">Get in touch</h3><p className="text-slate-600 dark:text-slate-400 mb-4">Have questions? We're here to help.</p><p>📧 info@mediscan.ai</p><p>🌐 www.mediscan.ai</p><p>📱 +1 (555) 123-4567</p></Card></div></Section>
}
function Chatbot(){const [open,setOpen]=useState(false); return <div className="fixed bottom-5 right-5 z-50"><button aria-label="Open AI chatbot" onClick={()=>setOpen(!open)} className="rounded-full bg-gradient-to-r from-cyan-500 to-blue-500 p-4 text-white shadow-xl hover:shadow-2xl hover:shadow-cyan-500/50"><Bot className="h-6 w-6"/></button>{open&&<div className="absolute bottom-20 right-0 w-80 rounded-2xl bg-white shadow-2xl dark:bg-slate-900 p-4 border border-slate-200 dark:border-slate-800"><h3 className="font-semibold mb-4">MediScan AI Assistant</h3><p className="text-sm text-slate-600 dark:text-slate-400">How can we help you today?</p></div>}</div>
}
function Footer(){return <footer className="border-t border-slate-200 px-4 py-10 text-center dark:border-slate-800"><b>MediScan AI</b><p className="mt-2 text-sm">Premium AI healthcare demo for educational purposes</p><p className="text-xs text-slate-500 dark:text-slate-400 mt-4">{disclaimer}</p></footer>
}

createRoot(document.getElementById('root')!).render(<App/>);
